patreon: hipersayanx
ko_fi: hipersayanx
liberapay: hipersayanx
custom: ["https://www.paypal.me/WebcamoidDonations", "https://commerce.coinbase.com/checkout/e5396fdc-119a-4287-bab9-383ea6332cdc", "https://gist.github.com/hipersayanX/0d575fc7b9b36a2e9817027fb50258bd"]
