env:
  NJOBS: 4

freebsd_task:
  env:
    COMPILER: clang
  freebsd_instance:
    matrix:
      image_family: freebsd-15-0-snap
      image_family: freebsd-14-0
    cpu: 2
    memory: 4G
  timeout_in: 60m
  install_script:
    - chmod +x ports/ci/freebsd/install_deps.sh
    - ./ports/ci/freebsd/install_deps.sh
  script:
    - chmod +x ports/ci/freebsd/build.sh
    - ./ports/ci/freebsd/build.sh
  deploy_script:
    - chmod +x ports/ci/freebsd/deploy.sh
    - ./ports/ci/freebsd/deploy.sh
