version: 8.8.0.{build}-{branch}
os: MinGW

image: Visual Studio 2019

platform:
  - x64

build:
  parallel: true
  verbosity: detailed

configuration:
  - release
#  - debug

environment:
  global:
    INSTALL_PREFIX: C:/projects/webcamoid/ports/deploy/temp_priv/usr
    # api key from https://bintray.com/profile/edit
    # encrypted with https://ci.appveyor.com/tools/encrypt
    BT_KEY:
      secure: UovqScFlz2shj+pxGyhQUYFiCvYJWEBGuhRCbaC3Bfxm0k9qo/pHYlp6Vx3jLIt9

  matrix:
    - PLATFORM: x86
      DAILY_BUILD: 1
    - PLATFORM: x64
      DAILY_BUILD: 1
    - PLATFORM: x86
      RELEASE_BUILD: 1
    - PLATFORM: x64
      RELEASE_BUILD: 1
    - PLATFORM: x86
    - PLATFORM: x64

install:
  - ports\ci\appveyor\environment_setup.bat
  - C:\msys64\usr\bin\bash -lc "cd /c/projects/webcamoid && ./ports/ci/appveyor/install_deps.sh"

build_script:
  - ports\ci\appveyor\environment_setup.bat
  - C:\msys64\usr\bin\bash -lc "cd /c/projects/webcamoid && ./ports/ci/appveyor/build.sh

after_build:
  - ports\ci\appveyor\environment_setup.bat
  - C:\msys64\usr\bin\bash -lc "cd /c/projects/webcamoid && ./ports/ci/appveyor/deploy.sh"
  - C:\msys64\usr\bin\bash -lc "cd /c/projects/webcamoid && ./ports/ci/appveyor/push_artifacts.sh"

deploy_script:
  - ports\ci\appveyor\environment_setup.bat
  - C:\msys64\usr\bin\bash -lc "cd /c/projects/webcamoid && ./ports/ci/appveyor/upload.sh"

notifications:
  - provider: Email
    to:
      - hipersayan.x@gmail.com
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: true
