version: 8.5.0.{build}-{branch}
os: MinGW

platform:
  - x86

build:
  parallel: true
  verbosity: detailed

configuration:
  - release
#  - debug

branches:
  only:
  - master

environment:
  global:
    FFMPEG_VERSION: 4.1
    GSTREAMER_VERSION: 1.14.4
    QMAKESPEC: win32-g++
    MAKETOOL: mingw32-make
    INSTALL_PREFIX: C:/projects/webcamoid/ports/deploy/temp_priv/root/usr

  matrix:
    - QTDIR: C:\Qt\5.11.2\mingw53_32
      TOOLSDIR: C:\Qt\Tools\mingw492_32
    - QTDIR: C:\Qt\5.11.2\mingw53_32
      TOOLSDIR: C:\Qt\Tools\mingw530_32
    - QTDIR: C:\Qt\5.11.2\msvc2015
      TOOLSDIR: C:\Qt\Tools\QtCreator
      QMAKESPEC: win32-msvc
      VSPATH: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC
      MAKETOOL: jom
    - QTDIR: C:\Qt\5.11.2\msvc2015_64
      TOOLSDIR: C:\Qt\Tools\QtCreator
      QMAKESPEC: win32-msvc
      PLATFORM: x64
      VSPATH: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC
      MAKETOOL: jom
    - QTDIR: C:\Qt\5.11.2\msvc2017_64
      TOOLSDIR: C:\Qt\Tools\QtCreator
      QMAKESPEC: win32-msvc
      PLATFORM: x64
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      VSPATH: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build
      MAKETOOL: jom

install:
  - ports\ci\appveyor\install_deps.bat

build_script:
  - ports\ci\appveyor\build.bat

on_success:
  - ports\ci\appveyor\deploy.bat

notifications:
  - provider: Email
    to:
      - hipersayan.x@gmail.com
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: true
