version: 8.1.0.{build}-{branch}
os: MinGW

platform:
  - x86

build:
  parallel: true
  verbosity: detailed

configuration:
  - release
#  - debug

branches:
  only:
  - master

environment:
  global:
    FFMPEG_VERSION: 3.3.3
    GSTREAMER_VERSION: 1.12.2
    QMAKESPEC: win32-g++
    MAKETOOL: mingw32-make
    INSTALL_PREFIX: C:/projects/webcamoid/ports/deploy/temp_priv/root

  matrix:
    - QTDIR: C:\Qt\5.6\mingw49_32
      TOOLSDIR: C:\Qt\Tools\mingw482_32
    - QTDIR: C:\Qt\5.7\mingw53_32
      TOOLSDIR: C:\Qt\Tools\mingw482_32
    - QTDIR: C:\Qt\5.6\mingw49_32
      TOOLSDIR: C:\Qt\Tools\mingw491_32
    - QTDIR: C:\Qt\5.7\mingw53_32
      TOOLSDIR: C:\Qt\Tools\mingw491_32
    - QTDIR: C:\Qt\5.6\mingw49_32
      TOOLSDIR: C:\Qt\Tools\mingw492_32
    - QTDIR: C:\Qt\5.7\mingw53_32
      TOOLSDIR: C:\Qt\Tools\mingw492_32
    - QTDIR: C:\Qt\5.6\mingw49_32
      TOOLSDIR: C:\Qt\Tools\mingw530_32
    - QTDIR: C:\Qt\5.7\mingw53_32
      TOOLSDIR: C:\Qt\Tools\mingw530_32
    - QTDIR: C:\Qt\5.6\msvc2013
      TOOLSDIR: C:\Qt\Tools\QtCreator
      QMAKESPEC: win32-msvc2013
      VSVER: 12
      MAKETOOL: jom
    - QTDIR: C:\Qt\5.7\msvc2013
      TOOLSDIR: C:\Qt\Tools\QtCreator
      QMAKESPEC: win32-msvc2013
      VSVER: 12
      MAKETOOL: jom
    - QTDIR: C:\Qt\5.6\msvc2013_64
      TOOLSDIR: C:\Qt\Tools\QtCreator
      PLATFORM: x64
      QMAKESPEC: win32-msvc2013
      VSVER: 12
      MAKETOOL: jom
    - QTDIR: C:\Qt\5.7\msvc2013_64
      TOOLSDIR: C:\Qt\Tools\QtCreator
      PLATFORM: x64
      QMAKESPEC: win32-msvc2013
      VSVER: 12
      MAKETOOL: jom
    - QTDIR: C:\Qt\5.6\msvc2015
      TOOLSDIR: C:\Qt\Tools\QtCreator
      QMAKESPEC: win32-msvc2015
      VSVER: 14
      MAKETOOL: jom
    - QTDIR: C:\Qt\5.7\msvc2015
      TOOLSDIR: C:\Qt\Tools\QtCreator
      QMAKESPEC: win32-msvc2015
      VSVER: 14
      MAKETOOL: jom
    - QTDIR: C:\Qt\5.6\msvc2015_64
      TOOLSDIR: C:\Qt\Tools\QtCreator
      PLATFORM: x64
      QMAKESPEC: win32-msvc2015
      VSVER: 14
      MAKETOOL: jom
    - QTDIR: C:\Qt\5.7\msvc2015_64
      TOOLSDIR: C:\Qt\Tools\QtCreator
      PLATFORM: x64
      QMAKESPEC: win32-msvc2015
      VSVER: 14
      MAKETOOL: jom

install:
  - ports\ci\appveyor\install_deps.bat

build_script:
  - ports\ci\appveyor\build.bat

on_success:
  - ports\ci\appveyor\deploy.bat

notifications:
  - provider: Email
    to:
      - hipersayan.x@gmail.com
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: true
