name: Android Basic

on: [push, pull_request]

env:
  QTVER_ANDROID: 6.7.2
  SDKVER: 11076708
  NDKVER: r27
  ANDROID_BUILD_TOOLS_VERSION: 34.0.0
  ANDROID_MINIMUM_PLATFORM: 24
  ANDROID_TARGET_PLATFORM: 34
  NJOBS: 4

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 10
      fail-fast: false
      matrix:
       include:
         - target_arch: armeabi-v7a
           upload: 0
         - target_arch: arm64-v8a
           upload: 0
         - target_arch: x86
           upload: 0
         - target_arch: x86_64
           upload: 0
         - target_arch: armeabi-v7a:arm64-v8a:x86:x86_64
           upload: 0
    env:
      TARGET_ARCH: ${{ matrix.target_arch }}
      UPLOAD: ${{ matrix.upload }}
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        chmod +x ports/ci/android-basic/install_deps.sh
        ./ports/ci/android-basic/install_deps.sh
    - name: Release Build
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      run: |
        chmod +x ports/ci/android-basic/build.sh
        ./ports/ci/android-basic/build.sh
    - name: Release Deploy
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      run: |
        chmod +x ports/ci/android-basic/deploy.sh
        ./ports/ci/android-basic/deploy.sh
    - name: Daily Build
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      env:
        DAILY_BUILD: 1
      run: |
        chmod +x ports/ci/android-basic/build.sh
        ./ports/ci/android-basic/build.sh
    - name: Daily Deploy
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      env:
        DAILY_BUILD: 1
      run: |
        chmod +x ports/ci/android-basic/deploy.sh
        ./ports/ci/android-basic/deploy.sh
